[package]
name = "number-theory"
version = "0.1.0"
authors = ["Sam Grayson <sam@samgrayson.me>"]

[dependencies]
clap = "2"
clippy = { version = "*", optional = true }
error-chain = "*"
image = "*"
#rayon = "0.9"
scarlet = "0.2.2"

# -C target-cpu=native -C lto -C opt-level=3
